export interface QuizDataItem {
  id: number;
  word: string;
  firstLetter: string;
  description: string;
  classname?: string;
  isAnswered: boolean;
}

export const quizData: QuizDataItem[] = [
  {
    id: 0,
    word: "Adventure",
    firstLetter: "A",
    description: "Exploring new and exciting places or experiences.",
    isAnswered: false,
    classname: undefined,
  },
  {
    id: 1,
    word: "Bicycle",
    firstLetter: "B",
    description: "A two-wheeled vehicle that is powered by pedaling.",
    isAnswered: false,
    classname: undefined,
  },
  {
    id: 2,
    word: "Cloud",
    firstLetter: "C",
    description: "A visible mass of water droplets in the atmosphere.",
    classname: undefined,
    isAnswered: false,
  },
  {
    id: 3,
    word: "Delicious",
    firstLetter: "D",
    description: "Having a pleasant taste or flavor.",
    classname: undefined,
    isAnswered: false,
  },
  {
    id: 4,
    word: "Elephant",
    firstLetter: "E",
    description: "A large mammal with a trunk, floppy ears, and tusks.",
    classname: undefined,
    isAnswered: false,
  },
  {
    id: 5,
    word: "Friendly",
    firstLetter: "F",
    description: "Being kind and amicable towards others.",
    classname: undefined,
    isAnswered: false,
  },
  {
    id: 6,
    word: "Garden",
    firstLetter: "G",
    description: "An area where plants, flowers, or vegetables are grown.",
    classname: undefined,
    isAnswered: false,
  },
  {
    id: 7,
    word: "Harmony",
    firstLetter: "H",
    description:
      "The combination of different elements to create a pleasing whole.",
    classname: undefined,
    isAnswered: false,
  },
  {
    id: 8,
    word: "Important",
    firstLetter: "I",
    description: "Having great significance or value.",
    classname: undefined,
    isAnswered: false,
  },
  {
    id: 9,
    word: "Journey",
    firstLetter: "J",
    description: "A trip or travel from one place to another.",
    classname: undefined,
    isAnswered: false,
  },
  {
    id: 10,
    word: "Kindness",
    firstLetter: "K",
    description: "The quality of being friendly, generous, and considerate.",
    classname: undefined,
    isAnswered: false,
  },
  {
    id: 11,
    word: "Library",
    firstLetter: "L",
    description:
      "A place where books and other resources are kept for reading or borrowing.",
    classname: undefined,
    isAnswered: false,
  },
  {
    id: 12,
    word: "Mystery",
    firstLetter: "M",
    description: "Something that is difficult to understand or explain.",
    classname: undefined,
    isAnswered: false,
  },
  {
    id: 13,
    word: "Nature",
    firstLetter: "N",
    description:
      "The physical world and everything in it, including plants, animals, and landscapes.",
    classname: undefined,
    isAnswered: false,
  },
  {
    id: 14,
    word: "Opportunity",
    firstLetter: "O",
    description: "A favorable or advantageous circumstance.",
    classname: undefined,
    isAnswered: false,
  },
  {
    id: 15,
    word: "Parade",
    firstLetter: "P",
    description:
      "A public procession, usually for celebration or demonstration.",
    classname: undefined,
    isAnswered: false,
  },
  {
    id: 16,
    word: "Quiet",
    firstLetter: "Q",
    description: "Making little or no noise; peaceful.",
    classname: undefined,
    isAnswered: false,
  },
  {
    id: 17,
    word: "Rainbow",
    firstLetter: "R",
    description:
      "A meteorological phenomenon with a spectrum of light appearing in the sky.",
    classname: undefined,
    isAnswered: false,
  },
  {
    id: 18,
    word: "Sunshine",
    firstLetter: "S",
    description: "Direct sunlight; the warmth and light provided by the sun.",
    classname: undefined,
    isAnswered: false,
  },
  {
    id: 19,
    word: "Treasure",
    firstLetter: "T",
    description: "Valuable items or possessions, often hidden or guarded.",
    classname: undefined,
    isAnswered: false,
  },
  {
    id: 20,
    word: "Universe",
    firstLetter: "U",
    description: "All of space, time, matter, and energy in existence.",
    classname: undefined,
    isAnswered: false,
  },
  {
    id: 21,
    word: "Victory",
    firstLetter: "V",
    description: "The state of having triumphed over an opponent or obstacle.",
    classname: undefined,
    isAnswered: false,
  },
  {
    id: 22,
    word: "Whisper",
    firstLetter: "W",
    description: "Speaking very softly, usually to avoid being heard.",
    classname: undefined,
    isAnswered: false,
  },
  {
    id: 23,
    word: "Xylophone",
    firstLetter: "X",
    description:
      "A musical instrument consisting of wooden bars played with mallets.",
    classname: undefined,
    isAnswered: false,
  },
  {
    id: 24,
    word: "Youthful",
    firstLetter: "Y",
    description: "Having the characteristics or qualities of youth; young.",
    classname: undefined,
    isAnswered: false,
  },
  {
    id: 25,
    word: "Zephyr",
    firstLetter: "Z",
    description: "A gentle, mild breeze.",
    classname: undefined,
    isAnswered: false,
  },
];
console.log(quizData);
